import '../styles/globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className="bg-orange-50" >
        <div className="flex flex-col items-center justify-center min-h-screen max-w-2xl mx-auto">
          {children}
        </div>
      </body>
    </html>
  );
}

