import Head from 'next/head';
import '../styles/globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
      </Head>
      <body className="bg-orange-50 scale-150" >
        <div className="flex flex-col items-center justify-center min-h-screen max-w-2xl mx-auto">
          {children}
        </div>
      </body>
    </html>
  );
}

